id = "8c8f8cf9-9144-4786-af91-757d8dad218f"
name = "Aster — Old Town"

[tiles]
wall = "#"
floor = " "

[spawn]
x = 48
y = 34
w = 2
h = 2

[meta]
tile_meters = 1
biome = "settlement"
notes = "Simplified plaza with large-entrance buildings."

[legend]
N = "npc"
S = "scarecrow"
P = "prop"
D = "door"
T = "text_hint"

[palette]
g = "#c7f9cc"
p = "#e8d5b5"
w = "#9ae1ff"
s = "#f3e5ab"
r = "#dddddd"
c = "#bdbdbd"

[[poi]]
id = "guild"
name = "Craftsmen's Guild"
x = 21
y = 28
kind = "building"

[[poi]]
id = "inn"
name = "Sailor's Rest Inn"
x = 78
y = 28
kind = "building"

[[poi]]
id = "market"
name = "Market Hall"
x = 21
y = 43
kind = "building"

[[poi]]
id = "annex"
name = "Temple Annex"
x = 78
y = 43
kind = "building"

grid = """
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                        ##########                              ##########                         
                        #        #                              #        #                         
                        #        #                              #        #                         
                        #        #                              #        #                         
                        #        #                              #        #                         
                        #        #                              #        #                         
                        #        #                              #        #                         
                        ####  ####                              ####  ####                         
            ##################                                       ##################            
            #                #                                       #                #            
            #                #                                       #                #            
            #                #                                       #                #            
            #                #                                       #                #            
            #                #                                       #                #            
            #                                                                         #            
            #                                                                         #            
            #                #                                       #                #            
            #                #                                       #                #            
            #                #                                       #                #            
            #                #                                       #                #            
            #                #                                       #                #            
            ##################                                       ##################            
                                                                                                   
            ##################                                       ##################            
            #                #                                       #                #            
            #                #                                       #                #            
            #                #                                       #                #            
            #                #                                       #                #            
            #                #                                       #                #            
            #                                                                         #            
            #                                                                         #            
            #                #                                       #                #            
            #                #                                       #                #            
            #                #                                       #                #            
            #                #                                       #                #            
            #                #                                       #                #            
            ##################                                       ##################            
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
"""

[layers.background]
grid = """
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwww                                                                                             
wwwwww                                                                                             
wwwwww                                                                                             
wwwwww                                                                                             
wwwwww                                                                                             
wwwwww                                                                                             
wwwwww                                                                                             
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
wwwwwwgggggggggggggggggggggggggggggggggggggggg       gggggggggggggggggggggggggggggggggggggggggggggg
"""

[exits]
left = "ac7304c4-0a75-4bc1-8cfb-c983519d371d"
right = "00b09d3c-ea4f-4056-a425-fc69471db727"
top = "954f791f-c7bf-4ebe-8ea2-cc4b2f9eacf5"
bottom = "7a23a047-5968-453e-8ff6-bb0acedcde53"

[[triggers]]
id = "plaza_welcome"
type = "text"
event = "onEnter"
x = 46
y = 32
w = 6
h = 6
text = "The heart of Aster hums with quiet trade."
