id = "d6b0a6a1-9f33-4edc-a3d5-8b22f6f1aa77"
name = "Cave"

[tiles]
wall = "#"
floor = " "

[spawn]
x = 2
y = 5
w = 2
h = 2

grid = """
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                          ####                     
                                                    ######################   #                     
                                                    #                        #                     
                                                    #                        #                     
                                                    #                        #                     
                                                    #                        #                     
                                                    #                        #                     
                                                    #                        #                     
                                                    #                        #                     
                                                    #                        #                     
                                                    #                        #                     
                                                    #                        #                     
                                                    #                        ##                    
                                                    ###########     ###########                    
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                          ##                       
                                                                         #  # ##                   
                                                                         #   ## ##                 
                                                                         #  ###  ##                
                                                                       ###### ##  #                
                                                                      ##  #########                
                                                                      #   ###### ##                
                                                                      ##  ######  ##               
                                                                       ######## #  #               
                                                                          ## ## ###                
                                                                           ##   #                  
                                                                             ####                  
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
"""

[layers.background]
grid = """
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
                                                                                                   
"""

[layers.labels]
grid = """

  ?

         !
"""

[layers.labels.legend]
"?" = "Glowing Spring"
"!" = "Collapsed Tunnel"

[exits]
left = "a1e4f9f0-55e8-4778-b0cc-0d6a6f1b0c11"
bottom = "61d3cae3-9ce6-4b1e-963c-1ab5dcd86204"
