id = "064136cb-5b9f-45ae-9f14-928f27b0bdda"
name = "Highland Watch"

[tiles]
wall = "#"
floor = " "

[spawn]
x = 12
y = 34
w = 2
h = 2

[meta]
tile_meters = 1
biome = "highland"
notes = "Wind-carved lookout with a bridge to the crystal door."

[legend]
N = "npc"
S = "scarecrow"
P = "prop"
D = "door"
T = "text_hint"

[palette]
g = "#c7f9cc"
p = "#e8d5b5"
w = "#9ae1ff"
s = "#f3e5ab"
r = "#dddddd"
c = "#bdbdbd"

grid = """
###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################
##################################                                #################################
####################################                              #################################
#####################################                              ################################
######################################                              ###############################
#######################################                              ##############################
########################################                              #############################
#########################################                              ############################
#########################################                              ############################
###########################################                            ############################
############################################                            ###########################
############################################                            ###########################
#############################################                          ############################
#############################################                          ############################
##############################################                         ############################
##############################################                        #############################
##############################################                        #############################
##############################################                        #############################
#############################################                        ##############################
#############################################                        ##                  ##########
#############################################                      ####                  ##########
############################################                      #####                  ##########
############################################                    #######   #   #   #      ##########
###########################################                    ########                  ##########
                    ######################  #                 #########                  ##########
                  #######################                    ##########                  ##########
                  #######################                  ############   #   #   #      ##########
                  #######################                  ############                  ##########
                  #####################                               #                  ##########
                  #####################             #            #    #                            
                  ###################               #            #    #   #   #   #                
                  ##################                #            #    #                          D 
                  #################                 #            #    #                            
                  #################                                   #                  ##########
                  ################         #        ###################   #   #   #      ##########
                  ###############                  ####################                  ##########
                  ###############                  ####################                  ##########
                  ###############                  ####################                  ##########
                  ###############                  ####################   #   #   #      ##########
                    #############               #  ####################                  ##########
################################                    ###################                  ##########
################################                    ###################                  ##########
################################                    ###################                  ##########
################################                      #############################################
################################    #     #                    ####################################
#################################                      ############################################
###############################                                  ##################################
##################################                        #########################################
#############################                                      ################################
####################################           #            #######################################
###########################                                          ##############################
#####################################                          ####################################
#########################                                              ############################
######################################                          ###################################
#######################                                                  ##########################
########################################                            ###############################
#########################################                            ##############################
########################################                              #############################
#########################################                              ############################
##########################################                              ###########################
##########################################                              ###########################
###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################
###################################################################################################
"""

[exits]
left = "94c93bb9-66ee-4be1-a1ff-1c484b02f77d"
right = "d0353fad-11be-4c30-b2a6-ef9dbf57ab4e"

[[triggers]]
id = "watch_plaque"
type = "text"
event = "onEnter"
x = 78
y = 28
w = 6
h = 4
text = "An old inscription: 'Guard the pass, guard the light.'"

[[triggers]]
id = "crystal_door"
type = "text"
event = "onEnter"
x = 94
y = 34
w = 4
h = 4
text = "A door cut into the cliff hums with crystal resonance."

