id = "7a23a047-5968-453e-8ff6-bb0acedcde53"
name = "Whispering Woods"

[tiles]
wall = "#"
floor = " "

[spawn]
x = 48
y = 8
w = 2
h = 2

[meta]
tile_meters = 1.0
biome = "woods"
notes = "Negative-space clearing and broad trails."

[legend]
N = "npc"
S = "scarecrow"
P = "prop"
D = "door"
T = "text_hint"

[palette]
g = "#c7f9cc"
p = "#e8d5b5"
w = "#9ae1ff"
s = "#f3e5ab"
r = "#dddddd"
c = "#bdbdbd"

grid = """
                                                                                                   
     #                                                                                             
   #####                                                 #                                         
   #####    #                                           ###                                        
  ####### #####        #                               #####   #                                   
   #####  #####       ###                               ###  #####                                 
   ##### #######     #####                               #   #####                   #      #      
     #   #######      ###                                   #######                 ###     ###    
          #####        #                                 ##  #####                   #      ###    
          #####                                         ##########                   #      ####   
            #     #            #                       ######  #                   #####    ###    
             #   ###         #####                     #######                     #####    ###    
            ###   ###        #####                      #######                   #######   #      
           ##### #####      #######                     ######                     #####           
            ###   ###        #####                        #         #              #####           
             #  #  #         #####  #              #              #####              #             
              #####            #   ###    #  #     ##             #####   #                   #    
    ##        #####                 #    #######   #             ####### ###                 ###   
   ##### ##  #######                      ######                  #####   #                   #    
  ########### #####                       ######                  #####                ##          
  ########### #####  #     #               #####                    #                  ##          
   ##############   ###   ###             ######                                      ###   #      
   ##########  #   #####   #              #####              #                #        ##          
   ##########       ###                  #######           #####            #####      ##   ##     
   #####  #          #                    #####            #####            #####           ##     
  #######                                ######           #######          #######      #   ###    
   #####           #   #                  ###              #####            #####           ##     
   #####          ########                                    ##            #####       #   ##     
     #             # #####                                                    #                    
    ###     #  #    #######         #                                                              
   #####   #######   #####       #                            #                                    
    ###   ########   #####    # ###                           #           #                        
     #     ########   ##     ### #  #                         ##         ###                       
            ######  #####   #####  ##                         #           # #                      
                                                                                                   
                                                                                                   
                                                                                                   
                    #####      ###                            ###                           ####   
                 ######       ###                             ####        #                 ###    
               ########        #                              ###       #####               ###    
               #########                                      ###       #####               #      
              #########                                       ##       #######    #                
               ########        #                              ##        #####    ###               
               ######        #####                            ###    #  #####    ##                
                 #          ######     #              ###  ######  #####  #     ###                
                           ########   ###              #   ####### #####         #                 
                           #######    ###                   ############# #                        
                          ########   #####         #        ##### ###### ###            #   #      
                        ########      ###          ##  #      #  ############           #   #      
                        ########       #  #        #######        #  #   ###           ##   ##     
                       #######           ###       #######                #             #   #      
                        #####           #####      ########                             #   #      
                        #####     #      ###         #####                                         
         #                #      ###      #          #####                       #     #           
        ###                     #####          #       #                        ###  ####          
       #####                     ###                  #            #           ##### ####   #      
        ###                       #                 #####   ##   #####          ### #####   ##     
         #                                          #####  ##### #####        #  #   ####   #      
                            #     #        #       ####### ############      ###     ####   ##     
                          #####  ###      ###      ###### ############        #        #    ###    
                          ##### #####      #       ######  ##### #####                      ##     
                         ###########           #   ####    ##### # #     #                  #      
                          #########                ##        #  ###     ###                        
                         #########                 ##            #     #####                       
    #         #           # #   #                                       ###                        
   ###       ###                                                         #                         
    #         #                                                                                    
                                                                                                   
                                                                                                   
                                                                                                   
"""

[layers.background]
grid = """
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg
"""

[exits]
right = "42a489d2-f15d-4a0b-9399-8b721ee0fb12"
top = "8c8f8cf9-9144-4786-af91-757d8dad218f"
bottom = "d0353fad-11be-4c30-b2a6-ef9dbf57ab4e"
